// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7eGFQJKyG8mcqHy7X9pOC9c8GHkdEeGU',
    appId: '1:1021462800837:web:6b3029d0834797def903ac',
    messagingSenderId: '1021462800837',
    projectId: 'mobileproject-823e9',
    authDomain: 'mobileproject-823e9.firebaseapp.com',
    storageBucket: 'mobileproject-823e9.appspot.com',
    measurementId: 'G-35F82M7G7R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACOmw2P2VpcPujF2Th5JuxBUk-2usDhcU',
    appId: '1:1021462800837:android:3697929fae386cddf903ac',
    messagingSenderId: '1021462800837',
    projectId: 'mobileproject-823e9',
    storageBucket: 'mobileproject-823e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe_tQ7q5EsN8dW7cqExlCGoZyDTfwhbXk',
    appId: '1:1021462800837:ios:80b738eaf0ca2b6bf903ac',
    messagingSenderId: '1021462800837',
    projectId: 'mobileproject-823e9',
    storageBucket: 'mobileproject-823e9.appspot.com',
    iosBundleId: 'com.example.twitty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe_tQ7q5EsN8dW7cqExlCGoZyDTfwhbXk',
    appId: '1:1021462800837:ios:f2f79d062a155a0ef903ac',
    messagingSenderId: '1021462800837',
    projectId: 'mobileproject-823e9',
    storageBucket: 'mobileproject-823e9.appspot.com',
    iosBundleId: 'com.example.twitty.RunnerTests',
  );
}
